version: '3.9'

services:
  # Next.js alkalmaz√°s
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: dusza-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ../.env
